# .buildkite/pipeline.yml
steps:
  - label: ":pipeline: Build kernel"
    timeout_in_minutes: 30
    agents:
      queue: "default"
    command: "build.sh"
    artifact_paths: "scripts/*"
    secrets:
      - TG_CHAT_ID
      - TG_TOKEN
